apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: book
  name: book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book
  strategy: {}
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
      - name: book
        image: docker.io/iwikil/my_book:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: my-db-secret
---

apiVersion: v1
kind: Service
metadata:
  name: book
spec:
  type: NodePort
  selector:
    app: book
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

      
        
