apiVersion: v1
kind: Pod
metadata:
  name: mypod1
spec:
  containers:
  - name: mypod1
    image: busybox
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
    command: ["/bin/sh","-c","sleep 1000"]
  volumes:
  - name: foo
    configMap:
      name: myconfigmap
